### ISSUE TITLE
Value not found error messages

### ISSUE THREAD

**Issue by bluebob** [signalfx/integrations#102]
Using the _collectd-elasticsearch_ plugin with ES version 2.3.2 (current production one on the Elastic website), and I'm getting "Value not found" messages for the following items:

indices.cache.filter.evictions, indices.cache.filter.size,
thread_pool.merge.active, thread_pool.merge.completed, thread_pool.merge.largest,
thread_pool.merge.queue, thread_pool.merge.rejected,
thread_pool.merge.threads, thread_pool.optimize.active,
thread_pool.optimize.completed, thread_pool.optimize.largest,
thread_pool.optimize.queue, thread_pool.optimize.rejected,
thread_pool.optimize.threads.

Rest of the metrics seem to be there, and the log indicates that the plugin is successfully recognising the version of ES. Any ideas why these metrics are generating the error message?

(Configuration: RHEL7/x64, CollectD 5.5.0 [source build], Python 2.7.5, ES 2.3.2 [Elastic's rpm])

**Comment by vzhabiuks** [comment]
Will start looking on this issue next week

**Comment by vzhabiuks** [comment]
In ES 2.X they have changed the set of metrics that are exposed. 'merge' and 'optimize' threadpool data is no longer there as well as indices.fielddata.memory_size_in_bytes and indices.filter_cache.evictions. 
Because of that the collectd logs corresponding warning messages but all other metrics will be collected the same way as before. 
Next week I will work on changing collectd-elasticsearch plugin to gather the right set of metrics for ES 2.X

**Comment by vzhabiuks** [comment]
Here is the fix https://github.com/signalfx/collectd-elasticsearch/pull/14

**Comment by bluebob** [comment]
Thanks vzhabiuks - just tried the fix version and everything looks like it's working for me now.
Quick work! :)

**Comment by vzhabiuks** [comment]
Welcome!
