### ISSUE TITLE
collectd-docker. Error: Unable to access Docker daemon. This may indicate SELinux problems

### ISSUE THREAD

**Issue by ksandrmatveyev** [signalfx/integrations#244]
Hello,
I have a trouble:
`docker : Unable to access Docker daemon at unix://var/run/docker.sock This may indicate SELinux problems. : ('Connection aborted.', error(13, 'Permission denied'))`

**Comment by charliesignalfx** [comment]
Hi @ksandrmatveyev,
I am sorry that the collectd-docker plugin is not behaving as expected.  In order to better troubleshoot the issue, could you please provide me a little bit of information about your deployment?

I would like to know:

- What OS, platform, and version you are using?
- What version of docker are you using?
- Can you please confirm that the docker service is running on the affected host?
- What is your SELINUX setting (enforcing, permissive, or disabled)?
- What is your SELINUXTYPE set to (targeted or mls)?
- Are you running collectd directly on the docker host, or is it running within a container?

Thank you in advance for getting this information, it will be useful in troubleshooting the issue further.
