### ISSUE TITLE
Elasticsearch 5.2 support

### ISSUE THREAD

**Issue by eperry** [signalfx/integrations#254]
None of the docs say that 5.2 is supported. Can we get the site updated with a statement if you know it is compatible and/or get it updated to handle 5.2

**Comment by molner** [comment]
Hello @eperry. The documentation both at https://github.com/signalfx/integrations/tree/master/collectd-elasticsearch as well as within the SignalFx app shows Elasticsearch 1.0.0 or later as supported with this integration.

It's my belief that this includes all 5.x version of Elasticsearch as well, as I've personally used it with ES 5.0 without issue and aren't aware of any changes in the minor releases since then that would cause issues for this integration. However, I will definitely verify that this is the case - and/or that someone has explicitly tested with ES 5.2 - and let you know.

In the meantime, are you experiencing a specific problem using this integration with ES 5.2, or are you just inquiring about support for that version before deploying it?

**Comment by eperry** [comment]
thanks for the quick comment, it is just in the next section you have listed all of the compatibilities and values from 1.0 to 2.3   so it was confusing.

I have been in the process of upgrading my whole environment and have discovered a lot of breaking changes so I wanted to make sure.

**Comment by molner** [comment]
Yes, the documentation could definitely be a bit more clear in that respect, especially with ES's huge jump from 2.x to 5.x versions a couple months back. Will see what we can do to make it better.

I can verify that this integration does in fact work with the latest version of Elasticsearch (5.2.2) - our automated testing around the integration as well as some quick spot verification this morning confirmed this. So you should be good to go once you complete your upgrade.
